name: Release Web
on:
  push:
    branches:
      - main

env:
  flutter-version: "3.10.0"

jobs:
  release-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "$flutter-version"
          channel: "stable"
          cache: true
      - name: Build
        run: flutter build web --base-href /raumunikate/
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
