name: Test
on:
  push:
    branches-ignore:
      - main
  workflow_run:
    workflows: [ "analyze.yml" ]
    types:
      - completed

jobs:
  needs: Analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter test
